# Generated by Django 4.0.5 on 2022-06-19 06:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classify',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_Pasien', models.CharField(max_length=100)),
                ('tanggal_Lahir', models.DateField()),
                ('nomer_Rekam_Medis', models.CharField(max_length=100)),
                ('gambar_Mammogram', models.ImageField(upload_to='raw_mammogram')),
                ('gambar_Mammogram_Contrast_Stretching', models.ImageField(upload_to='cs_mammogram')),
                ('hasil', models.CharField(choices=[('0', 'Normal'), ('1', 'Abnormal')], max_length=1)),
                ('tanggal_Skrining', models.DateTimeField(auto_now_add=True)),
                ('nama_Dokter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
